### ISSUE TITLE
CI

### ISSUE THREAD

**Issue by rexim** [YakPie/roguelike-for-stream#25]
I'd recommend to setup some kind of continuous integration for your project. So it can automatically check if any Pull Requests are compilable before merging them.

I usually use https://travis-ci.org/ and it works quite well with C/C++ projects https://docs.travis-ci.com/user/languages/c/

**Comment by TheKnarf** [comment]
Fixed in 605ae15d02c06fa5f00d4f595b6dd7cd51c59c88
